### ISSUE TITLE
Contents of viewed chest displayed on all other chests when sneaking

### ISSUE THREAD

**Issue by The-Zandrax** [PluginBugs/Issues-ChestPreview#2]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Zandrax

### What happened?

Hi, 

When I configure the plugin to see only when sneaking, the contents of the chest on which the action was performed first remains displayed, then you have to sneak again to no longer display it.
_(behavior provided for by the plugin? If so, would it be possible to deactivate it in the configuration so that you don't have to sneak again to have it displayed?)_ 

**Because this gives rise to an underlying problem:** if you forget to sneak again when looking at the chest to stop displaying it, the contents of the last chest will be displayed on each of the other chests you try to look at with sneak.*

*_I can't reproduce the bug at 100%, it seems random, I'll try to find the reproduction parameters that make it happen at 100%. If you ever fail to reproduce my case, consider only my suggestion for configuration and sneak._

### Steps to reproduce the issue

**For unwanted/desired behavior**

1. Configure the plugin on :  **standing, swimming, crawling :** _false_ and **sneaking :** _true_
2. Create two chests with different contents. 
3. Sneak on the first one. 
4. Stop looking at the first one when standing. 

**For the chest content display, which appears on all others**

1. Configure the plugin on :  **standing, swimming, crawling :** _false_ and **sneaking :** _true_
2. Create two chests with different contents. 
3. Sneak on the first one. 
4. Stop looking at the first one when standing.
5. Looking another chest and sneak again. 

### Server version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)

### ChestPreview Version

1.0.4

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.13

**Comment by DxrkCat** [comment]
```
graphics:
  trigger_distance_blocks: 4
  show_title: true
  brightness:
    block_light: 15
    sky_light: 15
  position:
    distance_y: 0.2
    distance_front: -1.0
  show_on_poses:
    standing: true
    sneaking: false
    crawling: false
    swimming: false
optimization:
  container_detection_interval_ticks: 1
containers:
  ender_chest: true
  jukebox: true
worlds:
- '*'

```
