### ISSUE TITLE
Stops displaying contents in chests

### ISSUE THREAD

**Issue by DxrkCxt** [PluginBugs/Issues-ChestPreview#5]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The plugin stops displaying the contents inside the chests after some time, that is, when you approach the chest does not appear ITEM_DISPLAY.

### Steps to reproduce the issue

How to reproduce: When AFK for over an hour (well I was away from the pc for that long) when I approach the chest again I can't see the contents. If I break it put it and put the same items in there again, it doesn't help. If I change the world or rejoin the server, everything works fine again.

### Server version

Purpur 1.20.2 2095

### ChestPreview Version

ver chestpreview
[16:43:25 INFO]: ChestPreview version 1.0.4

### ProtocolLib Version

ver ProtocolLib
[16:43:37 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-673
[16:43:37 INFO]: Provides read/write access to the Minecraft protocol.
[16:43:37 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

ver LoneLibs
[16:43:44 INFO]: LoneLibs version 1.0.31
[16:43:44 INFO]: Collection of libs used by my plugins
[16:43:44 INFO]: Authors: LoneDev and others

### FULL server log

No erros or warnings in logs

**Comment by DxrkCxt** [comment]
```
graphics:
  trigger_distance_blocks: 4
  show_title: true
  brightness:
    block_light: 15
    sky_light: 15
  position:
    distance_y: 0.2
    distance_front: -1.0
  show_on_poses:
    standing: true
    sneaking: false
    crawling: false
    swimming: false
optimization:
  container_detection_interval_ticks: 1
containers:
  ender_chest: true
  jukebox: true
worlds:
- '*'

```
